// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFaSzMBr9BQj_ZPYpuSrUrZDh94pKVi_w',
    appId: '1:218040185845:web:074a8f43854e8df430a6bc',
    messagingSenderId: '218040185845',
    projectId: 'safar-87c56',
    authDomain: 'safar-87c56.firebaseapp.com',
    storageBucket: 'safar-87c56.appspot.com',
    measurementId: 'G-LTE59HLWPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRTo5zNU59Tgz4tlbOCti7e--Qq9XhqCg',
    appId: '1:218040185845:android:d460814efe790a9430a6bc',
    messagingSenderId: '218040185845',
    projectId: 'safar-87c56',
    storageBucket: 'safar-87c56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBS7GW5LqSsWmhtSa6g9X_hbhs9h6r7DA',
    appId: '1:218040185845:ios:bfce7de2bfb6b81430a6bc',
    messagingSenderId: '218040185845',
    projectId: 'safar-87c56',
    storageBucket: 'safar-87c56.appspot.com',
    iosClientId: '218040185845-novm3lcbnkh5be9euls0c3nfh35kf1qh.apps.googleusercontent.com',
    iosBundleId: 'com.example.safareyaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBS7GW5LqSsWmhtSa6g9X_hbhs9h6r7DA',
    appId: '1:218040185845:ios:bfce7de2bfb6b81430a6bc',
    messagingSenderId: '218040185845',
    projectId: 'safar-87c56',
    storageBucket: 'safar-87c56.appspot.com',
    iosClientId: '218040185845-novm3lcbnkh5be9euls0c3nfh35kf1qh.apps.googleusercontent.com',
    iosBundleId: 'com.example.safareyaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFaSzMBr9BQj_ZPYpuSrUrZDh94pKVi_w',
    appId: '1:218040185845:web:0ad12ec89870b61a30a6bc',
    messagingSenderId: '218040185845',
    projectId: 'safar-87c56',
    authDomain: 'safar-87c56.firebaseapp.com',
    storageBucket: 'safar-87c56.appspot.com',
    measurementId: 'G-PS4S73VS4V',
  );
}
